/*
 * Copyright 2020 American Express Travel Related Services Company, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.americanexpress.dydaq.graphql.ddq.dynamicquery.demoproj.constants;

/**
 * Constant file generated by graphql-ddq plugin.Format it before using
 * Should be used to fetch metadata for entity Hospital.
 * Inner class AllColumns contains all the columns of the entity and can be used get the column name
 * Inner class Keys contains all the primary key annotated with @Id
 * Inner class JoinColumns contains columns annotated with @DynamicJoinColumn
 */
public class HospitalMeta {

    public static final String TABLE = "hospital_tbl";
    public static final String GRAPH_LEVEL = "rootObject";
    private HospitalMeta() {
    }

    public class AllColumns {
        public static final String HOSPITAL_ID = "hospital_id";
        public static final String NAME = "name";
        public static final String NO_OF_EMPLOYEES = "no_of_employees";
        public static final String CITY = "city";
        public static final String CONTACT_NO = "contact_no";
        private AllColumns() {
        }
    }

    public class Keys {
        public static final String HOSPITAL_ID = "hospital_id";

        private Keys() {
        }
    }

    public class JoinColumns {
        public static final String HOSPITAL_ID = "hospital_id";

        private JoinColumns() {
        }
    }

    public class Surgeon {

        public static final String TABLE = "surgeon_tbl";
        public static final String GRAPH_LEVEL = "surgeon";
        private Surgeon() {
        }

        public class AllColumns {
            public static final String SURGEON_ID = "surgeon_id";
            public static final String HOSPITAL_ID = "hospital_id";
            public static final String FULL_NAME = "full_name";
            public static final String DEPT_ID = "dept_id";
            public static final String CONTACT_NO = "contact_no";
            private AllColumns() {
            }
        }

        public class Keys {
            public static final String SURGEON_ID = "surgeon_id";

            private Keys() {
            }
        }

        public class JoinColumns {
            public static final String SURGEON_ID = "surgeon_id";
            public static final String HOSPITAL_ID = "hospital_id";
            public static final String DEPT_ID = "dept_id";
            public static final String CONTACT_NO = "contact_no";
            private JoinColumns() {
            }
        }

        public class DocSpeciality {

            public static final String TABLE = "doc_speciality_tbl";
            public static final String GRAPH_LEVEL = "surgeon_docSpeciality";
            private DocSpeciality() {
            }

            public class AllColumns {
                public static final String ID = "id";
                public static final String SURGEON_ID = "surgeon_id";
                public static final String SPECIALITY_ID = "speciality_id";
                public static final String EXPERIENCE = "experience";
                private AllColumns() {
                }
            }

            public class Keys {
                public static final String ID = "id";

                private Keys() {
                }
            }

            public class JoinColumns {
                public static final String SURGEON_ID = "surgeon_id";
                public static final String SPECIALITY_ID = "speciality_id";
                private JoinColumns() {
                }
            }

            public class Speciality {

                public static final String TABLE = "speciality_tbl";
                public static final String GRAPH_LEVEL = "surgeon_docSpeciality_speciality";
                private Speciality() {
                }

                public class AllColumns {
                    public static final String SPECIALITY_ID = "speciality_id";
                    public static final String SPECIALITY = "speciality";
                    private AllColumns() {
                    }
                }

                public class Keys {
                    public static final String SPECIALITY_ID = "speciality_id";

                    private Keys() {
                    }
                }
            }
        }
    }
}
