/*
 * Copyright 2020 American Express Travel Related Services Company, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.americanexpress.dydaq.graphql.ddq.dynamicquery.demoproj.constants;

/**
 * Constant file generated by graphql-ddq plugin.Format it before using
 * Should be used to fetch metadata for entity HospitalCount.
 * Inner class AllColumns contains all the columns of the entity and can be used get the column name
 * Inner class Keys contains all the primary key annotated with @Id
 * Inner class JoinColumns contains columns annotated with @DynamicJoinColumn
 */
public class HospitalCountMeta {

    public static final String TABLE = "hospital_tbl";
    public static final String GRAPH_LEVEL = "rootObject";
    private HospitalCountMeta() {
    }

    public class AllColumns {
        public static final String HOSPITAL_COUNT = "hospital_id";
        public static final String CITY = "city";
        private AllColumns() {
        }
    }
}
